model:
  _target_: src.agents.continual_td3.DiscountModelContinualTD3
  gamma: null
  sim_gamma: 0.9
  sim_horizon: 1
  buffer_size: 50_000
  p_real: 0

  # Key parameters: sim_gamma, sim_horizon, sim_buffer_size, buffer.beta
