defaults:
  - agent: pretrained_continual_td3/td3 # Arguments: td3, vanilla_tc_m2td3, stacked_tc_m2td3, oracle_tc_m2td3
  - schedule: static
  - _self_

master_seed: 2671232903
iterations: 1
seeds: ${seed_sequence:${iterations},${master_seed}}
env:
  name: halfcheetah
  max_episode_steps: 1_000_000
agent:
  radius: 0.01
  model:
    learning_starts: 10_000

num_gpus: 1 # Total physical GPUs available
gpu_slot_size: 4 # Jobs per GPU
parallel_task: ${int_product:${num_gpus},${gpu_slot_size}}

hydra:
  run:
    dir: outputs/${custom_dir:${agent},${env}}
