defaults:
  - agent: continual_td3/td3
  - schedule: brownian
  - experiments: null
  - override hydra/launcher: joblib
  - _self_

master_seed: 2671232903
seed: ${master_seed}
experiment_name: trial

iterations: 1
total_timesteps: 500_000
env:
  domain_randomization: true
  radius: 0.1
  augment_reward: true
# agent:
#   tensorboard_log: null

num_gpus: 1 # Total physical GPUs available
parallel_task: 2

hydra:
  mode: MULTIRUN
  launcher:
    n_jobs: ${parallel_task}
  sweep:
    dir: outputs/${experiment_name}
    subdir: ${custom_dir:${agent},${env},${schedule}}_${agent.model.sim_gamma}_${agent.model.current_episode_multiplier}
  sweeper:
    params:
      # env.id: choice(Ant-v5, HalfCheetah-v5, HumanoidStandup-v5, Walker2d-v5, Hopper-v5)
      ++env.id: choice(HalfCheetah-v5)
      ++seed: ${seed_sequence:${iterations},${master_seed}}
      agent: choice(continual_discounted_td3/td3)
      agent.model.sim_gamma: choice(0.85,0.9,0.95,0.99)
