defaults:
  - experiments: exp2
  - agent: pretrained_continual_td3/td3
  - schedule: brownian
  - override hydra/launcher: joblib_tests
  - _self_

experiment_name: null
master_seed: 2671232903
env:
  name: halfcheetah
  max_episode_steps: 300
agent:
  radius: 0.01
  model:
    learning_starts: 100
iterations: 1
seeds: ${seed_sequence:${iterations},${master_seed}}

num_gpus: 1 # Total physical GPUs available
gpu_slot_size: 4 # Jobs per GPU
parallel_task: ${int_product:${num_gpus},${gpu_slot_size}}

hydra:
  mode: MULTIRUN
  sweep:
    dir: outputs/${experiment_name}
    subdir: ${custom_dir:${agent},${env}}
  # sweeper:
  #   params:
  #     env.name: choice(ant, halfcheetah, humanoidstandup, walker2d)
#######################################

# defaults:
#   - pretrain: td3 # Arguments: td3, vanilla_tc_m2td3, stacked_tc_m2td3, oracle_tc_m2td3
#   - override hydra/launcher: joblib_tests
#   - _self_

# seed: 2671232903
# total_timesteps: 1e3

# num_gpus: 1 # Total physical GPUs available
# gpu_slot_size: 4 # Jobs per GPU
# parallel_task: ${int_product:${num_gpus},${gpu_slot_size}}

# hydra:
#   mode: MULTIRUN
#   sweep:
#     dir: outputs/pretrain
#     subdir: ${custom_dir:${agent},${env}}
#   sweeper:
#     params:
#       pretrain: choice(td3, vanilla_tc_m2td3, stacked_tc_m2td3, oracle_tc_m2td3)
#       env.name: choice(ant, halfcheetah, humanoidstandup, walker2d)
