defaults:
  - agent: continual_td3/td3
  - schedule: brownian
  - experiments: null
  - override hydra/launcher: joblib
  - _self_

master_seed: 2671232903
seed: ${master_seed}

iterations: 1
total_timesteps: 200
agent:
  model:
    learning_starts: 100
env:
  id: HalfCheetah-v5
  domain_randomization: true
  radius: 0.01

num_gpus: 1 # Total physical GPUs available
parallel_task: 1

hydra:
  mode: MULTIRUN
  launcher:
    n_jobs: ${parallel_task}
  sweep:
    dir: outputs/${experiment_name}
    subdir: ${custom_dir:${agent},${env},${schedule}}
  sweeper:
    params:
      # env.id: choice(Ant-v5, HalfCheetah-v5, HumanoidStandup-v5, Walker2d-v5, Hopper-v5)
      env.id: choice(HalfCheetah-v5)
      seed: ${seed_sequence:${iterations},${master_seed}}
