defaults:
  - pretrain: null
  - agent: vanilla_tc_m2td3
  - override hydra/launcher: joblib
  - _self_

master_seed: 2671232903
total_timesteps: 1e3
experiment_name: 0
# agent:
#   model:
#     learning_starts: 1000
env:
  id: HalfCheetah-v5

num_gpus: 1 # Total physical GPUs available
parallel_task: 1

hydra:
  mode: MULTIRUN
  launcher:
    n_jobs: ${parallel_task}
  sweep:
    dir: outputs/pretrain/${experiment_name}
    subdir: ${custom_dir:${agent},${env}}
  sweeper:
    params:
      # env.id: choice(Ant-v5, HalfCheetah-v5, HumanoidStandup-v5, Walker2d-v5, Hopper-v5)
      agent: choice(td3, stacked_tc_m2td3, vanilla_tc_m2td3, oracle_tc_m2td3)
