defaults:
  - pretrain: pretrain1
  - agent: td3
  - override hydra/launcher: joblib
  - _self_

seed: 2671232903
total_timesteps: 500
agent:
  model:
    learning_starts: 100

num_gpus: 1 # Total physical GPUs available
gpu_slot_size: 2 # Jobs per GPU
parallel_task: ${int_product:${num_gpus},${gpu_slot_size}}

hydra:
  mode: MULTIRUN
  launcher:
    n_jobs: ${parallel_task}
  sweep:
    dir: outputs/pretrain/${experiment_name}
    subdir: ${custom_dir:${agent},${env}}
  sweeper:
    params:
      +env.name: choice(ant, halfcheetah, humanoidstandup, walker2d) # Hopper is not used as the rrls implementation has some parameter issues
