defaults:
  - experiments: null
  - agent: pretrained_continual_td3/td3
  - schedule: brownian
  - override hydra/launcher: submitit_custom
  - _self_

master_seed: 2671232903
env:
  max_episode_steps: 1e5
agent:
  radius: 0.01
iterations: 10

num_gpus: 6 # Total physical GPUs available
gpu_slot_size: 4 # Jobs per GPU
parallel_task: ${int_product:${num_gpus},${gpu_slot_size}}

hydra:
  mode: MULTIRUN
  sweep:
    dir: outputs/${experiment_name}
    subdir: ${custom_dir:${agent},${env}}
  sweeper:
    params:
      +env.name: choice(ant, halfcheetah, humanoidstandup, walker2d) # Hopper is not used as the rrls implementation has some parameter issues
      +seed: ${seed_sequence:${iterations},${master_seed}}
