defaults:
  - pretrain: null
  - agent: td3
  - override hydra/launcher: joblib
  - _self_

seed: 2671232903
total_timesteps: 1e6

num_gpus: 6 # Total physical GPUs available
parallel_task: 40

hydra:
  mode: MULTIRUN
  launcher:
    n_jobs: ${parallel_task}
  sweep:
    dir: outputs/pretrain/${experiment_name}
    subdir: ${custom_dir:${agent},${env}}
  sweeper:
    params:
      +env.name: choice(ant, halfcheetah, humanoidstandup, walker2d) # Hopper is not used as the rrls implementation has some parameter issues

# Experiments control for shrink_factor
