defaults:
  - agent: td3
  - pretrain: null
  - override hydra/launcher: joblib
  - _self_

seed: 1568068674
total_timesteps: 5e6
env:
  id: Ant-v5
  domain_randomization: true

num_gpus: 6 # Total physical GPUs available
parallel_task: 40

hydra:
  mode: MULTIRUN
  launcher:
    n_jobs: ${parallel_task}
  sweep:
    dir: outputs/pretrain/${experiment_name}
    subdir: ${custom_dir:${agent},${env}}
  sweeper:
    params:
      env.id: choice(Ant-v5, HalfCheetah-v5, HumanoidStandup-v5, Walker2d-v5, Hopper-v5)
# Experiments control for shrink_factor
