defaults:
  - pretrain: td3 # Arguments: td3, vanilla_tc_m2td3, stacked_tc_m2td3, oracle_tc_m2td3
  - override hydra/launcher: submitit_custom
  - _self_

seed: 2671232903
total_timesteps: 1e6

num_gpus: 6 # Total physical GPUs available
gpu_slot_size: 4 # Jobs per GPU
parallel_task: ${int_product:${num_gpus},${gpu_slot_size}}

hydra:
  mode: MULTIRUN
  sweep:
    dir: outputs/pretrain
    subdir: ${custom_dir:${agent},${env}}
  sweeper:
    params:
      pretrain: choice(td3, vanilla_tc_m2td3, stacked_tc_m2td3, oracle_tc_m2td3)
      env.name: choice(ant, halfcheetah, humanoidstandup, walker2d) # Hopper is not used as the rrls implementation has some parameter issues
