defaults:
  - agent: continual_td3/td3
  - schedule: brownian
  - experiments: null
  - override hydra/launcher: joblib
  - _self_

master_seed: 1568068674
seed: ${master_seed}

num_gpus: 6 # Total physical GPUs available
parallel_task: 120
# max_threads: 2

env:
  domain_randomization: true

hydra:
  mode: MULTIRUN
  launcher:
    n_jobs: ${parallel_task}
  sweep:
    dir: outputs/${experiment_name}
    subdir: ${custom_dir:${agent},${env},${schedule}}
  sweeper:
    params:
      ++env.id: choice(Ant-v5, HalfCheetah-v5, HumanoidStandup-v5, Walker2d-v5, Hopper-v5)
      ++seed: ${seed_sequence:${iterations},${master_seed}}
  # Experiments control for schedules, radius vs discount factor, bootstrap with shrink factor
  job:
    env_set:
      # Set GPU ID per job
      CUDA_VISIBLE_DEVICES: "${modulus:${hydra:job.num},6}"
