defaults:
  - pretrain: td3 # Arguments: td3, vanilla_tc_m2td3, stacked_tc_m2td3, oracle_tc_m2td3
  - override hydra/launcher: joblib
  - _self_

seed: 2671232903
total_timesteps: 1e4
num_gpus: 1 # Total physical GPUs available
gpu_slot_size: 2 # Jobs per GPU
parallel_task: ${int_product:${num_gpus},${gpu_slot_size}}

hydra:
  launcher:
    n_jobs: ${parallel_task}
  mode: MULTIRUN
  sweep:
    dir: outputs/pretrain
    subdir: ${train_dir:${agent},${env}}
  sweeper:
    params:
      pretrain: choice(td3, vanilla_tc_m2td3, stacked_tc_m2td3, oracle_tc_m2td3)
      env.name: choice(ant, halfcheetah, hopper, humanoidstandup, walker2d)
# defaults:
#   - pretrain: td3 # Arguments: td3, vanilla_tc_m2td3, stacked_tc_m2td3, oracle_tc_m2td3
#   - _self_
# seed: 2671232903
# total_timesteps: 1e2

# hydra:
#   run:
#     dir: outputs/pretrain/${train_dir:${agent},${env}}
