defaults:
  - agent: pretrained_continual_td3/td3
  - schedule: brownian
  - experiments: null
  - override hydra/launcher: joblib
  - _self_

master_seed: 2671232903
seed: ${master_seed}

iterations: 10
total_timesteps: 200_000
env:
  id: Ant-v5
  domain_randomization: true
  # Set radius for environment
  radius: 0.01

num_gpus: 6 # Total physical GPUs available
parallel_task: 100

hydra:
  mode: MULTIRUN
  launcher:
    n_jobs: ${parallel_task}
  sweep:
    dir: outputs/${experiment_name}
    subdir: ${custom_dir:${agent},${env},${schedule}}
  sweeper:
    params:
      env.id: choice(Ant-v5, HalfCheetah-v5, HumanoidStandup-v5, Walker2d-v5, Hopper-v5)
      seed: ${seed_sequence:${iterations},${master_seed}}
# Experiments control for schedules, radius vs discount factor, bootstrap with shrink factor
