# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.LocalLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 6000
cpus_per_task: 10
gpus_per_node: ${num_gpus}
tasks_per_node: ${parallel_task}
mem_gb: 4
nodes: 1
name: ${hydra.job.name}
